#!/bin/bash

# This file calls the other scripts and should be added into (cut and
# pasted) the creation of an OpenStack instance.

Echo()
{
        echo "---> $@ <---"
}

Echo "Begin Customization:  Set tz=NYC"
timedatectl set-timezone America/New_York

Echo "Install git"
yum install -y git

Echo "Download helper scripts"
cd /usr/src
git clone http://github.com/chruck/zfsServerBuild
cd zfsServerBuild
chmod +rx installZfsOnFedora20 setupJasHome buildZfsFromGithub

Echo "Call Install ZFS script"
./installZfsOnFedora20
