#!/bin/bash
# For Fedora19,20:

# This file is expected to be called by the cloudinit subsystem,
# therefore as root.

if [[ "0" != "$(id -u)" ]] ; then
        echo "Run this program ${0} as root."
        exit 1
fi

Echo()
{
        echo "---> $@ <---"
}

AddZfsRepo()
{
        Echo "Adding ZFS repo"
        yum localinstall -y --nogpgcheck http://archive.zfsonlinux.org/fedora/zfs-release$(rpm -E %dist).noarch.rpm
}

FullUpdate()
{
        Echo "Package updates"
        yum update -y 
}

InstallMustHaves()
{
        Echo "Must-Haves"
        yum install -y screen bash-completion git mlocate zfs-dkms kernel-devel rpm-build which zlib-devel libuuid-devel
}

CreateJas()
{
        Echo "Create Jas"
        useradd jas
        #sudo sh -c "cat <<EOF >/etc/sudoers.d/91-cloud-init-users
        cat <<EOF >/etc/sudoers.d/91-cloud-init-users
# User jas has full access w/o passwd
jas ALL=(ALL) NOPASSWD:ALL
EOF
        #chmod +x /etc/sudoers.d/91-cloud-init-users

        Echo "Generate Jas' private key"
        su - jas sh -c "ssh-keygen -f ~jas/.ssh/id_rsa -N ''"

        Echo "Add Jas' key"
        cp ~fedora/.ssh/authorized_keys ~jas/.ssh
        chown jas:jas ~jas/.ssh/authorized_keys
}

SetupJas()
{
        chown jas:jas setupJasHome
        mv ~jas/.bashrc ~jas/.bashrc.old
        mv /zfsServerBuild/setupJasHome ~jas/.bashrc
        mv /zfsServerBuild/buildZfsFromGithub ~jas
}

Reboot()
{
        Echo "Reboot in order to be in new kernel, if it was updated"
        #reboot
        shutdown
}

#AddZfsRepo
FullUpdate
InstallMustHaves
CreateJas
SetupJas
Reboot
