#!/bin/bash
# For Fedora19,20:

# This file is expected to be called by the cloudinit subsystem,
# therefore as root.

if [[ "0" != "$(id -u)" ]] ; then
        echo "Run this program (${0}) as root."
        exit 1
fi

declare one="${1}"
declare toBuildRpms=false

Echo()
{
        echo "---> $@ <---"
}

CheckIfBuildRpms()
{
        if [[ "build" == "${one}" ]]; then
                toBuildRpms=true
        fi
}

AddZfsRepo()
{
        ${toBuildRpms} && return

        # The original method was to get the rpms from zfsonlinux.org,
        # but that requires building kernel modules.  Now that I have
        # those built kernel modules as RPMs, attach the NFS share and
        # get them from there.
        local viaZFSOnLinux=false

        if viaZFSOnLinux ; then
                Echo "Adding ZFS repo (zfsonlinux.org)"
                yum localinstall -y --nogpgcheck http://archive.zfsonlinux.org/fedora/zfs-release$(rpm -E %dist).noarch.rpm
        else
                # This section already done in cloudInit:
                Echo "(Re-)Adding ZFS repo (NFS mount 'fifteenth')"
                echo "130.127.193.179 fifteenth" >>/etc/hosts
                yum install -y nfs-utils
                mount fifteenth:/JasNFSPool /mnt
        fi
}

FullUpdate()
{
        Echo "Package updates"
        yum update -y 
}

InstallMustHaves()
{
        Echo "Must-Haves"
        #yum install -y screen bash-completion git mlocate
        yum install -y screen bash-completion mlocate
        #${toBuildRpms} && yum install -y zfs-dkms kernel-devel rpm-build which zlib-devel libuuid-devel
        if ${toBuildRpms} ; then
                Echo "Build Must-Haves"
                yum install -y zfs-dkms kernel-devel rpm-build zlib-devel libuuid-devel
        else
                Echo "Install ZFS RPMs that Jas built"
                pushd /mnt
                sudo rpm -Uvh \
                                kmod-zfs-$(uname -r)-0.6.3-*.x86_64.rpm \
                                kmod-spl-$(uname -r)-0.6.3-*.x86_64.rpm \
                                zfs-0.6.3-*.x86_64.rpm \
                                spl-0.6.3-*.x86_64.rpm \
                                libnvpair1-0.6.3*.x86_64.rpm \
                                libuutil1-0.6.3-*.x86_64.rpm \
                                libzfs2-0.6.3-*.x86_64.rpm \
                                libzpool2-0.6.3-*.x86_64.rpm

        fi
}

CreateJas()
{
        Echo "Create Jas"
        useradd jas
        #sudo sh -c "cat <<EOF >/etc/sudoers.d/91-cloud-init-users
        cat <<EOF >/etc/sudoers.d/91-cloud-init-users
# User jas has full access w/o passwd
jas ALL=(ALL) NOPASSWD:ALL
EOF
        #chmod +x /etc/sudoers.d/91-cloud-init-users

        Echo "Generate Jas' private key"
        su - jas sh -c "ssh-keygen -f ~jas/.ssh/id_rsa -N ''"

        Echo "Add Jas' key"
        cp ~fedora/.ssh/authorized_keys ~jas/.ssh
        chown jas:jas ~jas/.ssh/authorized_keys
}

SetupJas()
{
        chown jas:jas /usr/src/zfsServerBuild/setupJasHome
        mv ~jas/.bash_profile ~jas/.bash_profile.old
        cp /usr/src/zfsServerBuild/setupJasHome ~jas/.bash_profile
        ${toBuildRpms} && ln -s /usr/src/zfsServerBuild/buildZfsFromGithub ~jas
}

Reboot()
{
        Echo "Reboot in order to be in new kernel, if it was updated"
        #reboot
        shutdown -r
}

CheckIfBuildRpms
AddZfsRepo
FullUpdate
InstallMustHaves
CreateJas
SetupJas
Reboot
