#!/bin/bash
# For user jas to do:
sudo yum install -y git
mv .bashrc .bashrc.orig
mv .bash_profile .bash_profile.orig
git clone http://github.com/chruck/dot.bashrc.jas
ln -s dot.bashrc.jas/.bashrc.jas .bashrc
echo -e Jas Eckard\\neckard@clemson.edu | ./.bashrc
. .bashrc
mkprofile
